<x-app-layout>
    <x-home.hero></x-home.hero>
    <x-home.certificates></x-home.certificates>
    <x-home.about></x-home.about>
    <x-home.offer></x-home.offer>
    <x-home.first_visit></x-home.first_visit>
    <x-home.food_diary></x-home.food_diary>
    <x-home.contact></x-home.contact>
</x-app-layout>
